/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author henrique matheus
 */
public class ListaVIP extends javax.swing.JFrame {

    /**
     * Creates new form ListaVIP
     */
    public ListaVIP() {
        initComponents();
        
        jButton1.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBackground(new java.awt.Color(0,0,0,0));
        jButton4.setBackground(new java.awt.Color(0,0,0,0));
        jTextField1.setBackground(new java.awt.Color(0,0,0,0));
        jToggleButton1.setBackground(new java.awt.Color(0,0,0,0));
        jTable1.setBackground(new java.awt.Color(0,0,0,0));
        jButton5.setBackground(new java.awt.Color(0,0,0,0));
        
        
        
        
    }
    private PerfilDoCliente Chamar_Fornecedor = new PerfilDoCliente();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField11 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 480, 0, 10);

        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(360, 50, 710, 40);

        jToggleButton1.setBorder(null);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(1100, 40, 70, 60);

        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 259, 0, 1);

        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 640, 10, 0);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 690, 0, 10);

        jButton3.setBorder(null);
        getContentPane().add(jButton3);
        jButton3.setBounds(130, 640, 1, 1);

        jButton4.setBorder(null);
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 639, 1, 1);

        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(30, 10, 0, 14);

        jTextField3.setBorder(null);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(30, 40, 0, 14);

        jTextField4.setBorder(null);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(30, 70, 0, 14);

        jTextField5.setBorder(null);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(30, 100, 0, 14);

        jTextField6.setBorder(null);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(30, 130, 0, 14);

        jTextField7.setBorder(null);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(30, 160, 0, 14);

        jTextField8.setBorder(null);
        getContentPane().add(jTextField8);
        jTextField8.setBounds(140, 10, 0, 14);

        jTextField9.setBorder(null);
        getContentPane().add(jTextField9);
        jTextField9.setBounds(140, 40, 0, 14);

        jTextField10.setBorder(null);
        getContentPane().add(jTextField10);
        jTextField10.setBounds(140, 70, 0, 14);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome Do Cliente", "QTD Produtos Comprados", "Valor Gasto Pelo Cliente", "Numero", "Data", "Bairro", ".", "WhatsApp", "celular", "obiservaçâoes", "Cidade", ".", "Título 14", "Título 15", "Título 16"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);
        if (jTable3.getColumnModel().getColumnCount() > 0) {
            jTable3.getColumnModel().getColumn(0).setMinWidth(100);
            jTable3.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTable3.getColumnModel().getColumn(0).setMaxWidth(100);
            jTable3.getColumnModel().getColumn(1).setMinWidth(400);
            jTable3.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTable3.getColumnModel().getColumn(1).setMaxWidth(400);
            jTable3.getColumnModel().getColumn(2).setMinWidth(170);
            jTable3.getColumnModel().getColumn(2).setPreferredWidth(170);
            jTable3.getColumnModel().getColumn(2).setMaxWidth(170);
            jTable3.getColumnModel().getColumn(3).setMinWidth(170);
            jTable3.getColumnModel().getColumn(3).setPreferredWidth(170);
            jTable3.getColumnModel().getColumn(3).setMaxWidth(170);
            jTable3.getColumnModel().getColumn(4).setMinWidth(0);
            jTable3.getColumnModel().getColumn(4).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(4).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(5).setMinWidth(0);
            jTable3.getColumnModel().getColumn(5).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(5).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(6).setMinWidth(0);
            jTable3.getColumnModel().getColumn(6).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(6).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(7).setMinWidth(0);
            jTable3.getColumnModel().getColumn(7).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(7).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(8).setMinWidth(0);
            jTable3.getColumnModel().getColumn(8).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(8).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(9).setMinWidth(0);
            jTable3.getColumnModel().getColumn(9).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(9).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(10).setMinWidth(0);
            jTable3.getColumnModel().getColumn(10).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(10).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(11).setMinWidth(0);
            jTable3.getColumnModel().getColumn(11).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(11).setMaxWidth(0);
            jTable3.getColumnModel().getColumn(12).setMinWidth(0);
            jTable3.getColumnModel().getColumn(12).setPreferredWidth(0);
            jTable3.getColumnModel().getColumn(12).setMaxWidth(0);
        }

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(350, 130, 800, 520);

        jTextField11.setBorder(null);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField11);
        jTextField11.setBounds(100, 90, 0, 10);

        jButton5.setToolTipText("Sair Dessa Aba");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(1273, 3, 40, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Versão1.0.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setToolTipText("");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1320, 703);

        setSize(new java.awt.Dimension(1311, 701));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
           String filePath = ("C:\\Arquivos de Programas/Gestão de Clientes/Texto.txt");
        File file = new File(filePath);
        try {
             
            
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
           String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTable3.getModel();
           // model.setColumnIdentifiers(columnsName);

            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataMax = line.split("/");
             //   model.addRow(dataMax);
                
                String DataHoje = ":VIP";
                int posisao = 0;
                for (int j = 0; j < dataMax.length; j++) {
                    String  linha = dataMax[posisao];
                    //metodo para aparecer so o valor
                    if(linha.toLowerCase().contains(DataHoje.toLowerCase()) == true){
                         System.out.println(linha+"é vip"); 
                         
                         String linha1 = dataMax[posisao -13];
                         String linha2 = dataMax[posisao -12];
                         String linha3 = dataMax[posisao -11];
                         String linha4 = dataMax[posisao -10];
                         String linha5 = dataMax[posisao -9];
                         String linha6 = dataMax[posisao -8];
                         String linha7 = dataMax[posisao -7];
                         String linha8 = dataMax[posisao -6];
                         String linha9 = dataMax[posisao -5];
                         String linha10 = dataMax[posisao -4];
                         String linha11 = dataMax[posisao -3];
                         String linha12 = dataMax[posisao -2];
                         String linha13 = dataMax[posisao -1];
                         
                         DefaultTableModel val = (DefaultTableModel) jTable3.getModel();
                         val.addRow(new String[]{linha1, linha2, linha3, linha4, linha5, linha6, linha7, linha8, linha9, linha10, linha11, linha12, linha13, linha});
                         
                    }else{
                    System.out.println("Nao é vip");
                    }
                    posisao++;
                    }
                  }
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }       
        //table 2
        
         try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
            model.setColumnIdentifiers(columnsName);
            
            

            
            Object[] tableLines = br.lines().toArray();
            //model.addRow(tableLines);
            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);


            }
            
        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } 
                    
    }//GEN-LAST:event_formWindowOpened

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
      DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      jTable2.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                   JFCadrastro Tela = new JFCadrastro();
                   Tela.setVisible(rootPaneCheckingEnabled);
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
  
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         if(jTable2.getSelectedRow() != -1){
        
        System.out.print("Linha selecionada: "+jTable2.getSelectedColumn());
            
        DefaultTableModel dmz = (DefaultTableModel)jTable2.getModel();
        dmz.removeRow(jTable2.getSelectedRow());
 
         File file = new File("C:\\Arquivos de Programas/Gestão de Clientes/vip.txt");
       
        try {
        FileReader fr = new FileReader(file); 
        BufferedReader br = new BufferedReader(fr);
       
        
        String linha = br.readLine();
        ArrayList<String> salvar = new ArrayList();
        while(linha != null){
            

                    
            String nome = jTextField2.getText(); // nome 
            String email = jTextField3.getText(); // email
            String numero = jTextField4.getText(); //  numero 
            String bairro = jTextField5.getText(); // bairro
            String aniversario = jTextField6.getText(); // aniversario 
            String wats = jTextField7.getText(); //wats 
            String celular = jTextField8.getText(); // celular 
            String obiservacoes =jTextField9.getText(); // obiservaçoes 
            String rua = jTextField10.getText(); // rua

            
            
                  
            if(linha.equals(nome+";"+email+";"+numero+";"+bairro+";"+aniversario+";"+wats+";"+celular+";"+obiservacoes+";"+rua) == false){
                salvar.add(linha);
               // JOptionPane.showMessageDialog(null, nome+";"+email+";"+numero+";"+bairro+";"+aniversario+";"+wats+";"+celular+";"+obiservacoes+";"+rua);
            }
            linha = br.readLine();
        }

        br.close();
        fr.close();
        FileWriter fw2 = new FileWriter(file, true);
        fw2.close();
        
        FileWriter fw = new FileWriter(file);
        BufferedWriter bw = new BufferedWriter(fw);
        
            for (int i = 0; i < salvar.size(); i++) {
            bw.write( salvar.get(i) );
            bw.newLine();
            
            }
            bw.close();
            fw.close();
        } catch (IOException e) {
        }
        
        
         }else{
            JOptionPane.showMessageDialog(null, "Favor selecionar uma linha");
        } 
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
  /*        while (jTable2.getModel().getRowCount() > 0) {
    ((DefaultTableModel) jTable2.getModel()).removeRow(0);
    }
        
        
         String filePath = ("C:\\Arquivos do programa/vip.txt");
    File fie = new File(filePath);

    try {
        BufferedReader br = new BufferedReader(new FileReader(fie));
        String firstLine = br.readLine().trim();
        String[] columnsName = firstLine.split(",");
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
        //model.setColumnIdentifiers(columnsName);
        
        Object[] tableLines = br.lines().toArray();
        
        for(int i = 0; 1 < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split("/");
                model.addRow(dataRow);
            }

        } catch (Exception ex) {
            Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex);
        } /*/
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
      
            PerfilDoCliente frm2 = new PerfilDoCliente();
            
            TableModel model1 = jTable3.getModel(); 
     // TableModel model3 = jTextField8.getModel();
      int indexs[] = jTable3.getSelectedRows();
      
      jTextField11.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),0).toString()); //Nome
      Chamar_Fornecedor.txt_Endereco.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),0).toString()); //Nome
      
      Chamar_Fornecedor.txT_NomeUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),0).toString()); //Nome
      Chamar_Fornecedor.txT_EnderecoUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),4).toString()); //Numero
      Chamar_Fornecedor.txT_NumeroUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),6).toString()); //Data Aniversario
      Chamar_Fornecedor.txT_BairroUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),5).toString()); //Bairro
      Chamar_Fornecedor.txT_dataUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),2).toString()); //Data
      Chamar_Fornecedor.txT_AniversarioUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),7).toString()); //Aniversario
      Chamar_Fornecedor.txT_EmailUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),8).toString()); //Email
      Chamar_Fornecedor.txT_whatsUSUARIO1.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),9).toString()); //WhatsApp
      Chamar_Fornecedor.txT_CelularUSUARIO2.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),10).toString()); //Celular
      //Chamar_Fornecedor.txT_ObiservacoesUSUARIO1.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),12).toString()); // Obiservaçoes
      Chamar_Fornecedor.jTextField85.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),11).toString()); //verificaçõa
      
      
      
      
      
      Chamar_Fornecedor.txt_Nome.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),1).toString()); //Nome
      Chamar_Fornecedor.txt_Endereco.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),5).toString()); //Endereço
      Chamar_Fornecedor.txt_Numero.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),6).toString()); //Numero
      Chamar_Fornecedor.txt_Bairro.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),5).toString()); //Bairro
      Chamar_Fornecedor.txt_data.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),2).toString()); //Data
      Chamar_Fornecedor.txt_CodigoUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),0).toString()); //codigo
      Chamar_Fornecedor.txt_CidadeUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),13).toString()); //cidade
      
      
     // Chamar_Fornecedor.txT_AniversarioUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),9).toString()); //Aniversario
      Chamar_Fornecedor.txt_email.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),8).toString()); //Email
      Chamar_Fornecedor.txt_whats.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),10).toString()); //WhatsApp
      Chamar_Fornecedor.txt_celular.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),11).toString()); //Celular
      //Chamar_Fornecedor.txT_ObiservacoesUSUARIO1.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),12).toString()); // Obiservaçoes
      Chamar_Fornecedor.txt_cidade.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),12).toString()); //verificaçõa
      
      
    /*  frm2.txT_EnderecoUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),5).toString()); //Endereço
      frm2.txT_NumeroUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),7).toString()); //Numero
      frm2.txT_BairroUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),6).toString()); //Bairro
      frm2.txT_dataUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),2).toString()); //Data
      frm2.txT_AniversarioUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),8).toString()); //Aniversario
      frm2.txT_EmailUSUARIO.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),9).toString()); //Email
      frm2.txT_whatsUSUARIO1.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),10).toString()); //WhatsApp
      frm2.txT_CelularUSUARIO2.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),11).toString()); //Celular
      frm2.txT_ObiservacoesUSUARIO1.setText(jTable3.getModel().getValueAt(jTable3.getSelectedRow(),12).toString()); // Obiservaçoes  */
            
            
            
         if (!Chamar_Fornecedor.isVisible()) { Chamar_Fornecedor.setVisible(true); }
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
dispose();
PaginaUsuario Tela = new PaginaUsuario();
        Tela.setVisible(rootPaneCheckingEnabled);// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        DefaultTableModel model = (DefaultTableModel)jTable2.getModel();
      TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
      jTable2.setRowSorter(tr);
      tr.setRowFilter(RowFilter.regexFilter(jTextField1.getText().trim()));
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaVIP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaVIP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
