/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import static java.lang.System.out;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.FileWriter;
import java.io.Writer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henrique matheus
 */
public class MeuNegocio extends javax.swing.JFrame {

    /**
     * Creates new form MeuNegocio
     */
    public MeuNegocio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButtonPedidos = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonPedidos.setText("RESET");
        jButtonPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedidosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPedidos);
        jButtonPedidos.setBounds(820, 220, 60, 50);

        jButton2.setText("Salvar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 336, 63, 30);

        jLabel1.setText("resetarbanco de dados");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 130, 14);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 150, 36, 20);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Senha");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 200, 40, 20);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(370, 170, 210, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(370, 220, 210, 20);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(370, 290, 210, 20);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Palavra Chave");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 270, 80, 20);

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 160, 73, 23);

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 230, 100, 14);

        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1263, 3, 50, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/--- configurações.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1320, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //Apaga o txt"
        File file = new File("DadosLoguin.txt"); file.delete();
     //Cria u novo txt
     File f = new File("DadosLoguin.txt");
	try {
		f.createNewFile();
            PrintWriter pw = new PrintWriter(f);
            pw.println("loguin,jLabel2");
            pw.close();
	} catch (IOException e) {
		e.printStackTrace();
	}
        String palavra = jTextField3.getText();
        String Usuario = jTextField1.getText();
       String Senha = jTextField2.getText();
       
       RegistroDaTabela registroDaTabela = new RegistroDaTabela();
       
        registroDaTabela.setUser(jTextField1.getText());
        registroDaTabela.setSenha(jTextField2.getText());
        registroDaTabela.setPalavra(jTextField2.getText());
        try {
            JOptionPane.showMessageDialog(null, registroDaTabela.sauvado());  //Atençao
           
        } catch (Exception ex) {
            Logger.getLogger(PerfilDoCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedidosActionPerformed
       

    }//GEN-LAST:event_jButtonPedidosActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try{
        Writer out = new FileWriter("C:\\Arquivos do programa/apagando.txt");

    //limpa
    out.write("");
    out.flush();
    
    //escreve
    out.write("ABCdf");
    out.flush();
    out.close();
        
}catch(IOException e) {

}

String senha = jLabel6.getText();
 String sexo = JOptionPane.showInputDialog(null, "Digite sua senha para proseguir..." , "digite aqui", JOptionPane.PLAIN_MESSAGE);
         if (sexo.equalsIgnoreCase(senha)){
          JOptionPane.showMessageDialog(null, "Tabea foi apagada com sucesso"); 
          try{
        Writer out = new FileWriter("C:\\Arquivos do programa/apagando.txt");

    //limpa
    out.write("");
    out.flush();
    
    //escreve
    out.write("Codigo , Nome       , Data de Cadrastro    , Quantidade de Pedidos  , valor Pago , Endereço , Numero , Bairro , Aniversrio , Email, WhatsApp , celuar , Obiservações, Foto,oi,oi");
    out.flush();
    out.close();
        
}catch(IOException e) {

}
          
         }else{
         JOptionPane.showMessageDialog(null, "Senha invalida");
         }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 String filePath = ("C:\\Arquivos do programa/DadosLoguin.txt");
        File file = new File(filePath);
        //tabela 1
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine();
            String[] columnsName = firstLine.split(",");
            //DefaultTableModel model00 = (DefaultTableModel)jTable1.getModel();
            //model00.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();

            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
            //    model00.addRow(dataRow);
                System.out.println(dataRow[0]);
                System.out.println(dataRow[1]);
                //jLabel2.setText(dataRow[0]);
                jLabel6.setText(dataRow[1]);
                
            }
            
        } catch (Exception ex) {
           Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex); 
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
dispose();
TelaPrincipal tela = new TelaPrincipal();
                       tela.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MeuNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MeuNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MeuNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MeuNegocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MeuNegocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonPedidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
