/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import visão.ClasePrincipal;

/**
 *
 * @author henrique matheus
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        
        jButtonAcessar.setBackground(new java.awt.Color(0,0,0,0));
        jButton2.setBackground(new java.awt.Color(0,0,0,0));
        jButton3.setBackground(new java.awt.Color(0,0,0,0));
       
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jButtonAcessar = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButtonAcessar.setBackground(new java.awt.Color(4, 197, 130));
        jButtonAcessar.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jButtonAcessar.setForeground(java.awt.Color.white);
        jButtonAcessar.setBorder(null);
        jButtonAcessar.setBorderPainted(false);
        jButtonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAcessarActionPerformed(evt);
            }
        });
        jButtonAcessar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonAcessarKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonAcessar);
        jButtonAcessar.setBounds(340, 360, 120, 27);

        jTextFieldUsuario.setBackground(new java.awt.Color(84, 93, 106));
        jTextFieldUsuario.setForeground(java.awt.Color.white);
        jTextFieldUsuario.setBorder(null);
        jTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUsuarioActionPerformed(evt);
            }
        });
        jTextFieldUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldUsuarioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldUsuario);
        jTextFieldUsuario.setBounds(260, 210, 290, 30);

        jPasswordFieldSenha.setBackground(new java.awt.Color(84, 93, 106));
        jPasswordFieldSenha.setForeground(java.awt.Color.white);
        jPasswordFieldSenha.setBorder(null);
        jPasswordFieldSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenhaActionPerformed(evt);
            }
        });
        jPasswordFieldSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordFieldSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jPasswordFieldSenha);
        jPasswordFieldSenha.setBounds(260, 290, 290, 30);

        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 160, 0, 14);

        jTextField2.setAutoscrolls(false);
        jTextField2.setBorder(null);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(630, 190, 0, 14);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 110, 0, 0);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 140, 0, 0);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(782, 0, 0, 0);

        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(320, 430, 170, 30);

        jButton3.setToolTipText("Sair Do Programa");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(740, 0, 50, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGION AQUIUIOIII.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-250, -20, 1060, 600);

        setSize(new java.awt.Dimension(791, 560));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAcessarActionPerformed
     //do banco de dados 
        String User = jLabel2.getText();
        String senha = jLabel3.getText();
     //digitados
    String text1 =  jTextFieldUsuario.getText();
    String text2 = jPasswordFieldSenha.getText();
    
    
    //Date dataSistema = new Date();
       /// SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        
       
                    //metodo para aparecer so o valor
                    if(text1.toLowerCase().contains(User.toLowerCase()) == true){
                        
                         
                         if(text2.toLowerCase().contains(senha.toLowerCase()) == true){
                             
                         TelaPrincipal tela = new TelaPrincipal();
                         tela.setVisible(true);
                             dispose();
                         
                        
                         }else{
                        JOptionPane.showMessageDialog(null,"Senha ou Usuário Inválidos");
                    }
                         }else{
                        JOptionPane.showMessageDialog(null,"Senha ou Usuário Inválidos");
                    }
    
    
    
    
    
    
    if(text2.equals(User)){
    System.out.println("é igual");
    }else{
    System.out.println("não é igual");
    }
        
        
       // TelaPrincipal tela = new TelaPrincipal();
      //  tela.setVisible(true); //se se verdadeiro ele chama a tela 
    }//GEN-LAST:event_jButtonAcessarActionPerformed

    private void jTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUsuarioActionPerformed

    private void jPasswordFieldSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
 
  String filePath = ("C:\\Arquivos de Programas/Gestão de Clientes/DadosLoguin.txt");
        File file = new File(filePath);
        //tabela 1
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model00 = (DefaultTableModel)jTable1.getModel();
            model00.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();

            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
                model00.addRow(dataRow);
                System.out.println(dataRow[0]);
                System.out.println(dataRow[1]);
                jLabel2.setText(dataRow[0]);
                jLabel3.setText(dataRow[1]);
                
            }
            
        } catch (Exception ex) {
           Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
  String palavra  = JOptionPane.showInputDialog("Digite a Palavra Chave:", "Digite aqui");
  
  String filePath = ("C:\\Arquivos de Programas/Gestão de Clientes/DadosLoguin.txt");
        File file = new File(filePath);
  try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine();
            String[] columnsName = firstLine.split(",");
            DefaultTableModel model00 = (DefaultTableModel)jTable1.getModel();
            model00.setColumnIdentifiers(columnsName);
            
            Object[] tableLines = br.lines().toArray();

            
            for(int i = 0; i < tableLines.length; i++)
            {
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(";");
                model00.addRow(dataRow);
                
                String palavraChave = dataRow[2];
                
                if(palavra.toLowerCase().contains(palavraChave.toLowerCase()) == true){
                        
                         
                         
                             
                         TelaPrincipal tela = new TelaPrincipal();
                         tela.setVisible(true);
                         
                         }else{
                        JOptionPane.showMessageDialog(null,"Palavra Chave incorreta");
                    }
    
                
            }
            
        } catch (Exception ex) {
           Logger.getLogger(PaginaUsuario.class.getName()).log(Level.SEVERE, null, ex); 
        }
  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordFieldSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordFieldSenhaKeyPressed
if(evt.getKeyCode() == KeyEvent.VK_ENTER)  {  
 String User = jLabel2.getText();
        String senha = jLabel3.getText();
     //digitados
    String text1 =  jTextFieldUsuario.getText();
    String text2 = jPasswordFieldSenha.getText();
    
    
    //Date dataSistema = new Date();
       /// SimpleDateFormat formato = new SimpleDateFormat("dd-MM-yyyy");
        
       
                    //metodo para aparecer so o valor
                    if(text1.toLowerCase().contains(User.toLowerCase()) == true){
                        
                         
                         if(text2.toLowerCase().contains(senha.toLowerCase()) == true){
                             
                         TelaPrincipal tela = new TelaPrincipal();
                         tela.setVisible(true);
                             dispose();
                         
                        
                         }else{
                        JOptionPane.showMessageDialog(null,"senha e usuario incorreto");
                    }
                         }else{
                        JOptionPane.showMessageDialog(null,"senha e usuario incorreto");
                    }
    
    
    
    
    
    
    if(text2.equals(User)){
    System.out.println("é igual");
    }else{
    System.out.println("não é igual");
    }}
    // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenhaKeyPressed

    private void jButtonAcessarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonAcessarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonAcessarKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextFieldUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldUsuarioKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)  {
        jPasswordFieldSenha.requestFocus();
        }
    }//GEN-LAST:event_jTextFieldUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonAcessar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
